# Week 14-тэй ижил datasource тохиргоо
spring.datasource.url=jdbc:postgresql://localhost:5433/dvdrental
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA нэмэлт тохиргоо
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.property-naming-strategy=SNAKE_CASE

server.post=8080

